version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://quora:quora@db:5432/quoradb
      - DEBUG=True
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=quora
      - POSTGRES_PASSWORD=quora
      - POSTGRES_DB=quoradb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quora -d quoradb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:
  media_volume: