# Generated by Django 5.2 on 2025-04-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_userpreference_dislike_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userpreference',
            constraint=models.CheckConstraint(condition=models.Q(('dislike', True), ('like', True), _negated=True), name='not_both_true'),
        ),
    ]
