# Generated by Django 5.2 on 2025-04-09 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_userpreference_not_both_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preferences', to='webapp.answer'),
        ),
    ]
